services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    image: nginx
    environment:
      SERVER_NAME: ${SERVER_NAME}
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "9000:9000"

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/fatmanurcetintas/Desktop/githubinception/srcs/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/fatmanurcetintas/Desktop/githubinception/srcs/wordpress
      o: bind

# secrets:
#   db_password:
#     file: ../secrets/db_password.txt
#   db_root_password:
#     file: ../secrets/db_root_password.txt
#   credentials:
#     file: ../secrets/credentials.txt