services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - inception


networks:
  inception:
    driver: bridge
