services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    image: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb
    secrets:
      - credentials
      - db_password
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/facetint/data/mariadb
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/facetint/data/wordpress
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt